# Site settings
title: Purwadi
description: My Curriculum Vitae
favicon: /assets/img/icon.png
baseurl: 
url: 
rss_url: /pages/atom.xml
google_analytics: UA-69559226-3

# Pagination
paginate: 1
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [vendor]

# Author settings
author:
  name: Purwadi
  title: Web Developer
  address: Baros, Kota Cimahi, Jawa Barat, Indonesia
  email: purwadie97@gmail.com
  link: http://purwadipw.github.com
  weibo:
  github: PurwadiPw
  linkedin: purwadipw
  twitter: Purwadi073
  gavatar: /assets/img/purwadi.jpg
  stackoverflow: 
#  stackoverflow: 5995426
  educationHistory:
    - education1:
      organization: SD Negeri 2 Karangnongko
      location: Desa Karangnongko, Kecamatan. Mojosongo, Kabupaten Boyolali, Jawa Tengah
      degree: Lulus
      major: 
      started: 2003
      duration: (2003 - 2009)
      description: 
    - education2:
      organization: Mts Negeri Boyolali
      location: Jl. Kemuning, Banaran, Kec. Boyolali, Kabupaten Boyolali, Jawa Tengah
      degree: Lulus
      major: 
      started: 2009
      duration: (2009 - 2012)
      description: 
    - education3:
      organization: SMK Teknologi Industri Pembangunan Cimahi
      location: Jl. Mahar Martanegara No. 48 B, Kota Cimahi, Jawa Barat
      degree: Lulus
      major: Rekayasa Perangkat Lunak
      started: 2012
      duration: (2012 - 2013)
      description: 
  workHistory:
    - work1:
      company: D&X Company
      location: Buah Batu, Bandung, Jawa Barat
      title: Web Developer (Internship)
      started: 2015
      duration: (January - April)
      description: 
    - work2:
      company: PT. Softindo Computech
      location: Jl. PH.H. Mustofa, Surapati Core Blok F No.9, Bandung, Jawa Barat
      title: Web Developer
      started: 2015
      duration: (May - December)
      description: 
    - work3:
      company: PT. Aegis Ultima Teknologi
      location: Jln. Sekelimus VI No. 19 Bandung, Jawa Barat
      title: Fullstack Web Developer
      started: 2015
      duration: (December 2015 - present)
      description: 
  languages:
    - language1:
      name: Indonesian
      proficiency: Native
    - language2:
      name: Javanese
      proficiency: Native
    - language3:
      name: Sundanese
      proficiency: Native
    - language4:
      name: English
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: CSS
      percentage: 100%
    - skill3:
      name: Jquery
      percentage: 70%
    - skill3:
      name: Angular.js
      percentage: 70%
    - skill4:
      name: PHP
      percentage: 90%
    - skill5:
      name: Codeigniter
      percentage: 85%
    - skill6:
      name: Laravel
      percentage: 75%
    - skill7:
      name: Mysql
      percentage: 90%
    - skill8:
      name: Ruby on Rails
      percentage: 20%
    - skill9:
      name: Linux
      percentage: 85%
